import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./commonConponent/Sidebar";
import Navbar from "./commonConponent/Navbar";
import '../Css/Common.scss';
import { ReduxProvider } from '../@redux/ReduxProvider'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&family=Inconsolata:wght@200..900&family=Lilita+One&family=Oleo+Script:wght@400;700&family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Sora:wght@100..800&display=swap" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="container-fluid">
          <div className="row body h-100">
            <div className="col-12 col-md-2 p-0">
              <Sidebar />
            </div>
            <div className="col-12 col-md-10">
              <div className="row">
                <ReduxProvider>
                  <div className="col-12 p-0">
                    <Navbar />
                  </div>
                  <div className="col-12 p-3">
                    {children}
                  </div>
                </ReduxProvider>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}